### ISSUE TITLE
500 error ofter install on 6.6

### ISSUE THREAD

**Issue by Tim-VL** [thomaspeissl/Shopware-6-Blog-Plugin-MIT#1]
After manual upload and install in 6.6 it breaks Shopware for me.

Generates this error:

`Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "Cannot load resource "../../Controller". Make sure there is a loader supporting the "annotation" type." at Loader.php line 67 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): Cannot load resource \"../../Controller\". Make sure there is a loader supporting the \"annotation\" type. at /home/ax123525/domains/DOMAIN.com/public_html/stage/vendor/symfony/config/Loader/Loader.php:67)"} []`

**Comment by thomaspeissl** [comment]
It is only compatible with Shopware 6.5.

**Comment by Tim-VL** [comment]
Any plans for 6.6?
